# Generated by Django 2.2.10 on 2020-04-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='date_of_birth',
        ),
    ]
